// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: mqlakbjbvkvkuyvbhiwk

class SupabaseConfig {
  static const String supabaseUrl = 'https://mqlakbjbvkvkuyvbhiwk.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1xbGFrYmpidmt2a3V5dmJoaXdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM3NTI4MzYsImV4cCI6MjA3OTMyODgzNn0.cCznk6VZRLhXPNrcIsRdvwyYx2DHd-V0T9L15AdQemI';
}
